[package]
name = "apogeetrak"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features=["tiff", "png", "file_watcher"] }
chrono = "0.4.41"
rand = "0.9.2"
reqwest = "0.12.22"
serde = "1.0.219"
sgp4 = "2.3.0"
tokio = { version = "1", features = ["full"] }
